# Generated by Django 5.1.7 on 2025-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_qr/'),
        ),
    ]
