# Generated by Django 5.2.1 on 2025-05-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_trabajador_curp_trabajador_nss'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tipo_retraso',
            field=models.CharField(blank=True, choices=[('puntual', 'Puntual'), ('retardo_leve', 'Retardo leve'), ('retardo_alto', 'Retardo alto')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('proyectos', models.ManyToManyField(related_name='dispositivos', to='asistencia.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SesionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_base', models.DateTimeField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='asistencia.dispositivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='asistencia.proyecto')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('dispositivo', 'proyecto', 'fecha')},
            },
        ),
    ]
